### PR TITLE
Es2015

### PR DESCRIPTION
**Pull request by a8568730**
#### My PR
install babel-preset-es2015 and add it to babel config

#### Reason
I imported the plugin
```
import Throttle from 'superagent-throttle';
```
And got the error when webpack builds:
```
ERROR in bundle.js from UglifyJs
SyntaxError: Unexpected token: name (defaults) [./~/superagent-throttle/dist/index.js:12,0]
```
The dist/index.js didn't transform es6 classes to es5 functions.

### CODE REVIEW

**Comment by leviwheatcroft** [comment]
Whats your environment / node version?

**Comment by a8568730** [comment]
mint 18
node v6.10.0 (npm v3.10.10)

**Comment by leviwheatcroft** [comment]
Admittedly I find babel fairly confusing, but I'm not sure this is the best thing to do.

> SyntaxError: Unexpected token: name (defaults) [./~/superagent-throttle/dist/index.js:12,0]

line 12 of `dist/index.js` is `let defaults` ... so the problem isn't to do with es6 classes, but the `let` keyword which has been supported since node 4.

The `main` file (`dist/index`) runs fine in node 6.

If you're packing to `bundle.js`, then you should probably use the browser compat version as described in the [compatibility section](https://github.com/leviwheatcroft/superagent-throttle#compatibility) in the readme a la: `var Throttle = require('superagent-throttle/dist/browser')`

My understanding is that babel-preset-es2015 just runs *all* the es2015 plugins, which seems a little heavy handed.

**Comment by a8568730** [comment]
Thank you, I'll change to use the browser compat version for `bundle.js`.

Btw sorry I didin't say the words precisely
```
The dist/index.js didn't transform es6 classes to es5 functions.
```
What I meant is es6 syntax, not just `let` or `class`. :$

**Comment by leviwheatcroft** [comment]
No need to apologise mate.. I don't really know what I'm talking about either :)

**Pull request closed without merging**
